### PR TITLE
Initial conversion to 4.2 stable

### PR DESCRIPTION
**Pull request by nonunknown777**
Did all necessary conversion to 4.2 stable, most errors as possible I got!

things I couldnt find a solution i typed: `print_debug("TODO:....`

I hope this can help you get this working on 4.x soon, this plugin is awesome!!!

PS: I've cloned the main branch, updated to 4.2 then switched to godot4 branch and removed all files and placed the updated main.

### CODE REVIEW

**Comment by TheDuckCow** [comment]
Wow, a really incredible contribution! I'll be checking it out shortly and seeing how it's functioning.

You actually beat me to doing this, as I had started refreshing the godot 4 branch we had from awhile back. I've created a parallel [branch here](https://github.com/TheDuckCow/godot-road-generator/pull/143) which are changes made to make the auto conversion work more successfully, in the event we sign ourselves up for dual 4.x and 3.x support (so far hasn't been the plan, but indeed our feature completion version is still a little ways out). Maybe you have some ideas of other things we could port to that 3.5 compatible PR that you encountered? Either that, or we'll have to make parallel changes to both the 3.5 and 4.x branches, I'm not sure which is better at this stage.

**Comment by TheDuckCow** [comment]
Ok having checked out the branch, seems there's a little ways to go still - question, can you share a screen recording of how it's working for you in its current state on your branch? Could you also share roughly how much of this is just auto conversion, and how much is hand fixing? For reference, this is what I'm currently seeing, mostly just want to know if it's matching your side so we're on the same page.

https://youtu.be/V-tse9np5xc

What is working as-is on this branch from my end:
- All node types appearing and with icons
- The toolbar panel is appearing, though icons missing. The dropdown and styling of the dropdown is working (better than I managed so far on my own gd4 porting branch!)
- Export vars all appear on nodes added

What doesn't seem to be working
- The add mode of the toolbar, no visual indicator coming up
- The inspector panel for editing a roadpoint isn't loading (ie add/select next RP, and add/remove lanes with +/- buttons)
- Manually connecting to road points via their export var paths doesn't evidently trigger or successfully generate a RoadSegment

**Comment by nonunknown777** [comment]
Hmm, gdscript 2.0 is very different from 1.0(3.x) so keeping the two updated will be a lot of double work! I think you should only do bug/minor fixes in the 3.x version and improve the 4.x only since marjority of godot users tends to use the latest version!

what I mostly did was fixing the `get_configuration_warnings` which in 3.x was String but in 4.x is PackedStringArray.
Then also signal connections.
The harderst part was for undo_redo which you got from EngineInterface, so I did a little trick to get undo_redo for the road tool class!
and lastly @icon statements

**Comment by TheDuckCow** [comment]
Thanks for the info. Just for your awareness, what I'm probably going to do is merge this as-is into the godot4 branch we currently have, but as work continues it might be a force overwrite in the future (just so you are aware, but still get teh contribution credit).

On supporting 3x and 4x at the same time: Oh yes the syntax is too different for sure, the only way it would work is like so (and how I've approach the godot4 branch so far):

- Continue building in 3.x
- Use the project auto conversion tool in godot 4, mark that as a commit on its own as-is
- Apply a previously created git patch for the "manual" changes needed thereafter, created as another commit
- Fix what is hopefully only a minor extra bit of changes to get it the rest of the way working
- Finally, save an updated revised git patch based on the prior patch + the new hand changes (for future revisions of godot 4)

Still, indeed would be a lot of work and is a bit complicated. Really depends on how large that git patch has to be, which is the reason for [this PR ](https://github.com/TheDuckCow/godot-road-generator/pull/143) trying to make the auto conversion work better so the post patch can be smaller. For Wheel Steal, we do need to at least get the intersection support in order before fully adopting godot 4.0, but I'm dedicating myself to make sure we get get that before mid Jan so we can indeed fully adopt 4.0. We're also not that far off, since I'm assuming the first version of intersection support necessitates hand-crafted geo (not ideal, but still at least workable) with a good-enough workflow showing how people can create their own.

**Review by TheDuckCow — APPROVED** [review]
As mentioned, will merge this as-is, even though it's not quite useable in this state. Will continue to update this as we go along, but this at least gets the godot4 branch more up to date.

**Comment by dev-bre** [comment]
I tried this branch but it keeps failing on adding the RoadContainer and RoadPoints.

**Pull request merged**
