### PR TITLE
This change is to catch empty gizmos array before it spam floods the console (godot 4.3rc3) and cancels before emitting on_transform signal

### PR DESCRIPTION
**Pull request by FishOfTheNorthStar**

### CODE REVIEW

**Review by TheDuckCow — COMMENTED** [review]
Thanks for the PR! Odd that we had a similar fix hinted at in the godot 3 branch but not in godot 4.

Just one clarifying comment below if you have an idea one way or the other

**Comment by FishOfTheNorthStar** [comment]
Hey np I was just trying it out and bumped into this issue kinda early on.  I haven't really had a chance to dig into it much yet, but from glancing through it a moment, I'd guess 'yes, go ahead and emit (seems weird that it wouldn't), but if the complete absence of any gizmos is something that could break other processes using that signal, then perhaps the gizmo collection itself could be passed as a signal parameter, and those handlers could then independently check if gizmos is valid before taking action.  It seems like there generally would be a gizmo so this is some kind of weird edge case.  But in those rare edge cases, maybe listeners would want to catch it, and null out the output until a valid setup is detected, something like that.

For me, I intend to do almost all of my road generation procedurally, so everything involving gizmos or editor-based changes will largely go unused.  It would be fantastic to have some kind of 'minimal UI' option or variant version of the road points designed for this, ie they have no gizmos, no handles, you don't drag them around or anything like that:  just provide with a path and if the output is marked invalid (it's initial state or any time the path is changed), recreate it either automatically or signal a 'road needs regenerated' so other systems could cancel that if necessary (like in the event a large world scene is loading in for the first time and the procedural road points are derived from not-yet-ready ground points, etc.

I'm not sure I'll be able to use road generator for my purposes (elevated super highways ala Fallout 4), but I'm going to try so if I need to make adjustments to fit my use case I may commit them and put in a PR just so you can have a look (but not actually merge, unless you actually like whatever it is i changed).  I'm looking into some kind of integration with Proton Scatter, which would be very helpful for me.  Ultimately I need to dynamically damage the roads too, which could get... messy.

**Comment by TheDuckCow** [comment]
Thanks for the explanation @FishOfTheNorthStar, and agreed I do also think it's an edge case. It might be to do with scene initialization, where a lot of built in signals get fired as properties are loaded and trigger their assignee functions.

Procedural placement is also our primary edge case for Wheel Steal game ([see here](https://x.com/WheelStealGame/status/1820683872771969059)), for which this road generator project started. But, indeed there is some functionality that could be better gated to the UI alone. Generally though, it already behaves as you describe - if you have auto refresh = true on the parent road manager, then it'll automatically regenerate outdated road segments. If you want to fully control when and how the generation happens, you can turn that off and manually trigger it on a roadpoint by roadpoint basis (something we do in Wheel Steal, so that we can plot out road points along a path before we actually get close enough to warrant generating the geometry)

Your use case seems quite reasonable and what the addon was made for! Please do share the struggle and pain points you run into so we can try to prioritize that. One thing I've been considering is adding better built in support for adding railings and under-side geo of roads, but in the meantime you should be able to leverage the auto generated [edge curves](https://x.com/TheDuckCow/status/1764198830067880250).

**Comment by TheDuckCow** [comment]
I'm aligned with your thinking in the meantime, will merge. Thanks for the contribution!

**Comment by FishOfTheNorthStar** [comment]
Hey great, thanks.  Game looks great btw, gl.  So I was looking through my code and I notice a lot of what i'm doing gets bogged down in generating parking lots, then intersections between parking lots and roads, and it occured to me maybe you'd find that interesting because if your road generator could also generate basic parking lots with same eventual system of interconnects and intersections, that'd really be very useful, for me at least.  That's probably what i'll be focused on here in my own modifications to road gen.

Another eventual goal is to take a road system (and related parking lots / building foundations) and bake it to an elevation map more or less like how terrain systems use.  Then in my procedural terrain generation, I have a step already that overlays an elevation stencil on top of the generated heights, to handle stuff like 'trees that have a bit of ground interaction like root structures that raise the ground a bit near the trunk', etc.  It'll handle roads/lots fine too though.

So I do intend to dig into the code soon and start chopping stuff up, when I do I'll post it for review and possible integration.  I find myself wondering though... how do you feel about GDextensions?  or an entirely c# implementation?  GD script is pretty great but everything else I'm doing is c# so they aren't playing well together too much yet.  Whatever I post might be in C, or C#, but if you prefer GD script I'll make sure we can get anything I cook up ported over, there's really nothing C can do that GD script can't, they just don't interoperate super well yet.

BTW sometimes I'll chat up a thread a lot just hashing out ideas, it's fun.  But if you'd rather close this thread down, and move the convo to a forum or whatever, just drop a link to whereever is best.

**Comment by TheDuckCow** [comment]
Hey @FishOfTheNorthStar!

Sounds like you indeed have a lot of experience with generative work! Hey if you're open to it, I'd love to find a way where we can mutually work towards the same goals and make such tools more broadly available. I've not been able to work even on procedural intersections, which really should be a key baseline feature, we've just not had time to focus on it. If you ever want to hold a live call to chat through ideas or product direction, I'm available.

>  bake it to an elevation map more or less like how terrain systems use.

Sounds very similar to what I have in [mind here](https://github.com/TheDuckCow/godot-road-generator/issues/144), as I mentioned in my last post there, this is an area that - given a standard surface to project onto or to use for projection (UX question on the best approach for that), it shouldn't be that difficult of a feature to implement I'd say.

> So I was looking through my code and I notice a lot of what i'm doing gets bogged down in generating parking lots, then intersections between parking lots and roads

It's a very interesting point you make. I, too, in generating roads for games have already run into the need for making parking lots or other areas like that. It's hard to imagine exactly how a took like that could work without entering the realm of becoming a more general purpose procedural modeling tool. That being said, I'd be curious to explore the idea further, and how you think such a tool would work.

Of course can't guarantee we'd get there, but if you don't mind exploring the idea, them I'm down to chat! Why don't you copy the tidbit about parking lots into a new ticket [over here](https://github.com/TheDuckCow/godot-road-generator/issues/new) so there's a place to continue the conversation when we get a chance, since PR chats here will get lost to time.

> Hey great, thanks. Game looks great btw, gl. 

Thanks! It's the slow-but-steady journey

**Comment by TheDuckCow** [comment]
Oh and I skipped this question

>  how do you feel about GDextensions? or an entirely c# implementation?

I'm open to it, I'm just not as technically skilled in that area. I do get that gdscript long term won't be the most performant approach, but have been hoping that it was serve as good enough for more rapid development. Once the project sunsets 3.x new dev support and we're all in for 4.x (a goal before end of year), it could be a more suitable moment to review options and tradeoffs there. If you really don't mind porting to gdscript that does help, but if there are performance gain arguments for critical path proc gen, I'd be open to more seriously consider GDextensions

**Pull request merged**
