### PR TITLE
Establish RoadManager controls and updates

### PR DESCRIPTION
**Pull request by TheDuckCow**
Purpose of this PR is to establish the hierarchy and controls of the RoadManager node, intended to be the parent of all Road* nodes, along with some appropriate triggers and settings.

This PR also covers a number of QoL improvements including in-editor warnings and instructions, and native ability to add road nodes from the create menu.

### CODE REVIEW

**Comment by TheDuckCow** [comment]
Here's what the updated icons look like now. Curious if you have any feedback before I merge these icons @bdog2112. Not looking for as much of a thorough testing this time, might be better to have you do one larger round of testing as I make further progress (but I'll still be breaking into several PRs along the way).

road-generator-icons

I've also locally set up a command line test runner, which eventually we could use to automate testing via github actions (once we figure out how to cache godot binaries between runs). For now, manually copying over.

```
Totals
Scripts:          4
Passing tests     17
Failing tests     0
Risky tests       0
Pending:          0
Asserts:          71 of 71 passed

17 passed 0 failed.  Tests finished in 1.6s
```

**Comment by bdog2112** [comment]
> Here's what the updated icons look like now.

I think I like your proposed icons the best. To make sure, I mocked up some RoadPoint icons with circles instead of rectangles. The main intent was to observe the association between the word "point" and the circle. But, I felt like what I saw was more akin to clown juggling balls. ;-) Hence, I recommend sticking with the rectangular RoadPoint icons.

The outline around the your RoadContainer perfectly implies that it contains RoadPoints.

The map is also a great reference for a series of RoadContainers. So, again, good choice.

Didn't you rename "LaneSegments" to "RoadLanes"? If so, then the curve icon is perfect for them! So, yeah. Stick with the icons you proposed in your post.

_Example Of Juggling Balls As RoadPoints_:
RoadGen Icons

Did you ask me to test something? If so, please let me know. It sounded like you were planning to do testing later.

**Comment by TheDuckCow** [comment]
Thanks @bdog2112 and super appreciate the idea of the circle/point! I also toyed with it quite a bit and never found something that I liked. Actually might be fun, for prosperity, to show some of the other iterations below here (also noting this early feedback I got on twitter)

No need for further testing, might have you do one round of more exhaustive testing once I've got more of the intersection system in place. Carry on with your curvy roadwork in the meantime in the WheelSteal project!

https://twitter.com/WheelStealGame/status/1705997712163045809

And the other variations:

image

image

And various iterations of nodes that I quickly tried and replaced in the editor (unfortunately didn't save those screenshots, so this is straight from Affinity)

Screen Shot 2023-10-07 at 3 44 05 PM

**Comment by TheDuckCow** [comment]
There's even a couple others here I tried but tossed out and I coudln't get files for, I experimented with having RoadPoints be the lane widget arrow with or without a point or square in the middle, never quite felt good with the pixels we had to play with.

**Pull request merged**
